name: CI with Cache Example

on: [push]

jobs:
  cache-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: prime-cache-59a11fc
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: cache-59a11fc

      - name: prime-cache-59a11fc
        run: |
          echo "Cache hit: ${{ steps.cache-deps.outputs.cache-hit }}"
        # This will print 'Cache hit: true' if cache existed, 'Cache hit: false' if not

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
