name: Cache hit/miss test

on: [push]

jobs:
  test-cache:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: cache-59a11fc

    - name: prime-cache-59a11fc
      run: echo "Cache hit: ${{ steps.cache-deps.outputs.cache-hit }}"
